### ISSUE TITLE
Multus SEGV during ndt container setup

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/k8s-support#69]
```
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf1a378]
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: goroutine 1 [running]:
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: main.cmdAdd(0xc42029f960, 0x0, 0x0, 0x0, 0x0, 0xc4200aa140, 0x5, 0x5, 0x0)
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]:         /tmp/tmp.GDjXxA013Z/src/github.com/intel/multus-cni/multus/multus.go:249 +0x698
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: main.main.func1(0xc42029f960, 0x1130920, 0x5)
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]:         /tmp/tmp.GDjXxA013Z/src/github.com/intel/multus-cni/multus/multus.go:334 +0x53
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc4202c93c0, 0xc42029f960, 0x1854de0, 0xc42009e510, 0x11a9958, 0x0, 0xc4200bfe58)
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]:         /tmp/tmp.GDjXxA013Z/src/github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:175 +0x19f
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc4202c93c0, 0x11a9958, 0x11a9960, 0x11a9968, 0x1854de0, 0xc42009e510, 0x11558b8, 0x2f, 0x0)
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]:         /tmp/tmp.GDjXxA013Z/src/github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:210 +0x2f9
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0x11a9958, 0x11a9960, 0x11a9968, 0x1854de0, 0xc42009e510, 0x11558b8, 0x2f, 0xc)
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]:         /tmp/tmp.GDjXxA013Z/src/github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:275 +0x118
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0x11a9958, 0x11a9960, 0x11a9968, 0x1854de0, 0xc42009e510, 0x11558b8, 0x2f)
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]:         /tmp/tmp.GDjXxA013Z/src/github.com/intel/multus-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:290 +0x7a
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: main.main()
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]:         /tmp/tmp.GDjXxA013Z/src/github.com/intel/multus-cni/multus/multus.go:332 +0x72
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: E0801 15:02:33.154188    1663 cni.go:260] Error adding network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
Aug 01 15:02:33 mlab3.lga03.measurement-lab.org kubelet[1663]: E0801 15:02:33.154200    1663 cni.go:228] Error while adding to cni network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
```

**Comment by kokosta** [comment]
Obsolete.
